services:
  maria_db:
    container_name: "$CONTAINER_NAME"
    image: mariadb
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_USER: "${DB_USER}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "4030:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql